// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSjTBnE8jepNiIiLKikTqUvchHrMPUYQI',
    appId: '1:987084638923:web:eb5b0ff23ecaed3945a94e',
    messagingSenderId: '987084638923',
    projectId: 'eventify-6e0f4',
    authDomain: 'eventify-6e0f4.firebaseapp.com',
    storageBucket: 'eventify-6e0f4.firebasestorage.app',
    measurementId: 'G-ZZKYD02TLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJkkY3XpqknXqwEjfkIAneoW_WvpayfmU',
    appId: '1:987084638923:android:f741d475f0824d6045a94e',
    messagingSenderId: '987084638923',
    projectId: 'eventify-6e0f4',
    storageBucket: 'eventify-6e0f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpnHubyFd0hQVUsAoBdmULudom-HCTK3g',
    appId: '1:987084638923:ios:56fe0742b7cdc2fa45a94e',
    messagingSenderId: '987084638923',
    projectId: 'eventify-6e0f4',
    storageBucket: 'eventify-6e0f4.firebasestorage.app',
    iosBundleId: 'com.example.eventify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpnHubyFd0hQVUsAoBdmULudom-HCTK3g',
    appId: '1:987084638923:ios:56fe0742b7cdc2fa45a94e',
    messagingSenderId: '987084638923',
    projectId: 'eventify-6e0f4',
    storageBucket: 'eventify-6e0f4.firebasestorage.app',
    iosBundleId: 'com.example.eventify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSjTBnE8jepNiIiLKikTqUvchHrMPUYQI',
    appId: '1:987084638923:web:133faf4e09e9a3a645a94e',
    messagingSenderId: '987084638923',
    projectId: 'eventify-6e0f4',
    authDomain: 'eventify-6e0f4.firebaseapp.com',
    storageBucket: 'eventify-6e0f4.firebasestorage.app',
    measurementId: 'G-4F5CKNJGZY',
  );
}
